layout: sidebar

style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: false
    projects:
      - profclems.github.io

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: clementsam75
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 5433233
  # telegram: your_username
  twitter: clems_dev
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: PHP
    web_url: https://github.com/topics/php
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/php/php.png

  - name: Go
    web_url: https://github.com/topics/go
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/go/go.png
    
  - name: ASP.NET Core
    web_url: https://github.com/topics/aspnet
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/aspnet/aspnet.png
    
  - name: Laravel 
    web_url: https://github.com/topics/laravel
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/laravel/laravel.png 
    
  - name: Vue.js 
    web_url: https://github.com/topics/vue
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/vue/vue.png
  
  - name: Docker
    web_url: https://github.com/topics/laravel
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png
    
  - name: Amazon Web Service
    web_url: https://github.com/topics/aws
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/aws/aws.png
    
  - name: API
    web_url: https://github.com/topics/api
    
  - name: Data Structures
    web_url: https://github.com/topics/data-structure
